<h1>Zestawy komputerowe</h1>  
<table id="background-image">  
    <thead>  
        <tr scope="col" >  
            <th>lp.</th>  
            <th>Nazwa</th>  
               <th>Numer</th> 	
                <th>U¿ytkownik</th> 	
                <th>Data</th> 	
                <th>Procesor</th> 	
                <th>plyta</th> 	
                <th>chipset</th> 	
                <th>pamiec</th> 	
                <th>grafika</th> 	
                <th>dzwiek</th> 	
                <th>hdd</th> 	
                <th>odd</th> 	
                <th>rozmiar</th> 	
                <th>ip</th> 	
               <th>mac</th> 	
               <th>nic</th> 	
                <th>modem</th> 	
                <th>drukarka</th>
        </tr>  
    </thead>  
    <tbody>  
        <?php foreach ($this->lista as $k => $lista): ?>  
            <tr>  
                <td><?php echo ($k + 1) ?>.</td>  
                <td><?php echo $lista['system'] ?></td>  
                <td><?php echo $lista['numer'] ?></td>  
                <td><?php echo $lista['user'] ?></td>  
                <td><?php echo $lista['data'] ?></td>  
                <td><?php echo $lista['procesor'] ?></td>  
                <td><?php echo $lista['plyta'] ?></td>  
                <td><?php echo $lista['chipset'] ?></td>  
                <td><?php echo $lista['pamiec'] ?></td>
                <td><?php echo $lista['grafika'] ?></td>  
                <td><?php echo $lista['dzwiek'] ?></td>  
                <td><?php echo $lista['hdd'] ?></td>
                <td><?php echo $lista['odd'] ?></td>
                <td><?php echo $lista['rozmiar'] ?></td>  
                <td><?php echo $lista['ip'] ?></td>  
                <td><?php echo $lista['mac'] ?></td>
                   <td><?php echo $lista['nic'] ?></td>
                <td><?php echo $lista['modem'] ?></td>  
                <td><?php echo $lista['drukarka'] ?></td>          
            </tr>  
        <?php endforeach; ?>  
           
    </tbody>  
</table> 
<?php echo 'Razem szuk:'. ($k + 1)?>